export const authConstants = {

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
    PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
    PASSWORD_RESET_FAILURE: "PASSWORD_RESET_FAILURE",

    CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
}

export const postConstants = {
    GET_ALL_POST_REQUEST: 'GET_ALL_POST_REQUEST',
    GET_ALL_POST_FAILURE: 'GET_ALL_POST_FAILURE',
    GET_ALL_POST_SUCCESS: 'GET_ALL_POST_SUCCESS',

    GET_POST_BY_USER_REQUEST: 'GET_POST_BY_USER_REQUEST',
    GET_POST_BY_USER_FAILURE: 'GET_POST_BY_USER_FAILURE',
    GET_POST_BY_USER_SUCCESS: 'GET_POST_BY_USER_SUCCESS',

    GET_POST_BY_SLUG_REQUEST: 'GET_POST_BY_SLUG_REQUEST',
    GET_POST_BY_SLUG_FAILURE: 'GET_POST_BY_SLUG_FAILURE',
    GET_POST_BY_SLUG_SUCCESS: 'GET_POST_BY_SLUG_SUCCESS',

    GET_POST_BY_ID_REQUEST: 'GET_POST_BY_ID_REQUEST',
    GET_POST_BY_ID_FAILURE: 'GET_POST_BY_ID_FAILURE',
    GET_POST_BY_ID_SUCCESS: 'GET_POST_BY_ID_SUCCESS',

    ADD_POST_REQUEST: 'ADD_POST_REQUEST',
    ADD_POST_FAILURE: 'ADD_POST_FAILURE',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',

    DELETE_POST_BY_ID_REQUEST: 'DELETE_POST_BY_ID_REQUEST',
    DELETE_POST_BY_ID_FAILURE: 'DELETE_POST_BY_ID_FAILURE',
    DELETE_POST_BY_ID_SUCCESS: 'DELETE_POST_BY_ID_SUCCESS',

    UPDATE_POST_REQUEST: 'UPDATE_POST_REQUEST',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',

    DOAWNLOAD_POST_REQUEST: 'DOAWNLOAD_POST_REQUEST',
    DOAWNLOAD_POST_FAILURE: 'DOAWNLOAD_POST_FAILURE',
    DOAWNLOAD_POST_SUCCESS: 'DOAWNLOAD_POST_SUCCESS',
}


